name = "ACE3 Capri Sun"
prefix = "ACE3_Capri_Sun"
mainprefix = "z"

[version]
major = 0
minor = 0
patch = 0
git_hash = 8

[properties]
author = "UAG Development Team"
url = "https://github.com/uagpmc/arma3"